name:                queueBot
version:             0.1.1.0
github:              "githubuser/queueBot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/queueBot#readme>

ghc-options:
- -W
- -Werror
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-partial-fields
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- directory
- aeson
- text
- haskell-tdlib

library:
  language:    GHC2021
  source-dirs: src
  default-extensions:
  - DuplicateRecordFields
  - NoFieldSelectors
  - OverloadedStrings
  - OverloadedRecordDot
  - LambdaCase

executables:
  queueBot-exe:
    language:    GHC2021
    main:                Main.hs
    source-dirs:         app
    ghc-options: 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queueBot
    default-extensions:
    - DuplicateRecordFields
    - NoFieldSelectors
    - OverloadedStrings
    - OverloadedRecordDot
    - LambdaCase

tests:
  queueBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queueBot
